### PR TITLE
Selecting the scope for the client in DI

### PR DESCRIPTION
**Pull request by Kingmidas74**
Add options to change DI lifetime for NClient.
1) general Add.. methos now has optional parameter ServiceLifeTime (singleton by default)
2) Many new extensions like Add...Singleton(), Add...Transient(), etc.

### CODE REVIEW

**Comment by Kingmidas74** [comment]
@smolchanovsky

**Comment by smolchanovsky** [comment]
Great job! But the test coverage is confusing: 37.0% Coverage

**Comment by Kingmidas74** [comment]
> Great job! But the test coverage is confusing: 37.0% Coverage

So... which type of test do you want? There are only method overloads without any logic. I'm open to any offers

**Comment by smolchanovsky** [comment]
> > Great job! But the test coverage is confusing: 37.0% Coverage
> 
> So... which type of test do you want? There are only method overloads without any logic. I'm open to any offers

I agree with you, logic is pretty simple, but we should have tests to protect us from typos. For example, method must create singleton instance, but creates scoped

**Comment by Kingmidas74** [comment]
So.. Is it enough now?

**Comment by Kingmidas74** [comment]
> > > Great job! But the test coverage is confusing: 37.0% Coverage
> > 
> > 
> > So... which type of test do you want? There are only method overloads without any logic. I'm open to any offers
> 
> I agree with you, logic is pretty simple, but we should have tests to protect us from typos. For example, method must create singleton instance, but creates scoped

so.. is it enough now?

**Review by smolchanovsky — APPROVED** [review]
Cool!

**Pull request merged**
